### ISSUE TITLE
Missing update of tab Arguments after editing a function prototype

### ISSUE THREAD

**Issue by tmcdos** [crypto2011/IDR#12]
In file **EditFunctionDlg.cpp**, in function **TFEditFunctionDlg_11011981::bApplyTypeClick**, on row **305** there is a call to **FillType()** - but there is no call to **FillArgs()**. As a result, when you modify a prototype, you have to close the form and reopen it in order to see the changes on tab **Arguments**.

**Comment by crypto2011** [comment]
Fixed
