### ISSUE TITLE
Add var section to Source Code

### ISSUE THREAD

**Issue by csitGenny** [crypto2011/IDR#18]
# Decompiler result look like this:
```
procedure TForm1.Button4Click(Sender: TObject);
var
  TmpS: AnsiString;
begin//0
  //0044FF6C
  EBX := Self;
  try
    //0044FF83
    ESI := $FF7FFFFF{-8388609};
    EDX := 8;
    EAX := ESI;
    TmpS := IntToHex(ESI, {8});
    EDX := TmpS;
    EAX := Memo1;
    EAX := Memo1.FLines;
    EAX := Memo1.FLines.Add(TmpS);
  finally//1
    //0044FFB8
    TmpS := '';
  end;//1
end;//0
```

**Comment by csitGenny** [comment]
Modify:

1. TDecompileEnv::DecompileProc()

//add prototype
    PInfoRec _recN = GetInfoRec(StartAdr);
    ProcName = _recN->GetName();
    AddToBody(_recN->MakePrototype(StartAdr, true, false, false, true, false));

    **//add vars -- Insert by ZGL
    if (_recN->procInfo->locals && _recN->procInfo->locals->Count > 0)
    {
        AddToBody("var");
        for (int n = 0; n < _recN->procInfo->locals->Count; n++)
        {
            PLOCALINFO locInfo = PLOCALINFO(_recN->procInfo->locals->Items[n]);
            String line = "  " + GetLvarName(locInfo->Ofs);
            if (locInfo->TypeDef == "")
                line += ": ?;";
            else
                line += ": " + locInfo->TypeDef + ";";
            AddToBody(line);
        }
    }
    ///////////////////////////**

    AddToBody("begin");


2. TDecompileEnv::GetLvarName(int Ofs)
{
    //Insert by ZGL
    PInfoRec _recN = GetInfoRec(StartAdr);
    if (_recN->procInfo->locals)
    {
        for (int n = 0; n < _recN->procInfo->locals->Count; n++)
        {
            PLOCALINFO locInfo = PLOCALINFO(_recN->procInfo->locals->Items[n]);
            if (locInfo->Ofs == Ofs - LocBase && locInfo->Name != "")
                 return locInfo->Name;
        }
    }
    ////////////////
    return String("lvar_") + Val2Str0(LocBase - Ofs);
}


3. TFEditFunctionDlg_11011981::bApplyVarClick

catch (Exception &E)
    {
        ShowMessage("Invalid size");
        edtVarSize->SetFocus();
        return;
    }

    //Insert by ZGL
    PInfoRec recN = GetInfoRec(Adr);
    PLOCALINFO locInfo = PLOCALINFO(recN->procInfo->locals->Items[lbVars->ItemIndex]);
    ////////////

    item = edtVarName->Text;
    locInfo->Name = item;  //ZGL add
    if (item != "")
        line += item;
    else
        line += "?";
    line += ":";
    item = edtVarType->Text;
    locInfo->TypeDef = item;  //ZGL add
    if (item != "")
        line += item;
    else
        line += "?";

**Comment by crypto2011** [comment]
I have modyfied source files. Thank you very much, csitGenny! And I have idea about naming local vars (like IDA style). One more idea: make source code output colored like disasm and add function of changing local vars name and type with following decompilation.

**Comment by csitGenny** [comment]
It's great idea!

**Comment by csitGenny** [comment]
The modyfy of TFEditFunctionDlg_11011981::bApplyVarClick in EditFunctionDlg.cpp not complete.

    item = edtVarName->Text;
    **locInfo->Name = item;  //ZGL add**
    if (item != "")
        line += item;
    else
        line += "?";
    line += ":";
    item = edtVarType->Text;
    **locInfo->TypeDef = item;  //ZGL add**
    if (item != "")
        line += item;
    else
        line += "?";
