### ISSUE TITLE
About const parameter

### ISSUE THREAD

**Issue by csitGenny** [crypto2011/IDR#19]
About constant (const) parameter, in current  version of IDR, all treated as variable (var) parameters.
For example: 
function CompareStr(const S1, S2: string): Integer; 
In IDR, we get the follow result:
function CompareStr(var S1:  AnsiString; var S2: AnsiString): Integer;

I have correct this problem.

**Comment by csitGenny** [comment]
# Modify:

## 1.TFMain_11011981::StrapProc

//Get Args
        if (!recN->MakeArgsManually())
        {
            BYTE callKind = ProcInfo->CallKind;
            recN->procInfo->flags |= callKind;

            int aa = 0, ss = 8;
            ARGINFO argInfo;
            p = ProcInfo->Args;
            if (p)
            {
                for (int k = 0; k < ProcInfo->ArgsNum; k++)
                {
                    argInfo.Tag = *p; p++;
                    int locflags = *((int*)p); p += 4;
                    **if ((locflags & 7) == 1) argInfo.Tag = 0x23;  //Add by ZGL**
                    argInfo.Register = (locflags & 8);
                    //Ndx

**Comment by crypto2011** [comment]
I have modyfied source files. Thank you very much, csitGenny!
