### ISSUE TITLE
Bug:PropagateClassProp

### ISSUE THREAD

**Issue by Pigrecos** [crypto2011/IDR#2]
I'am Testing program(( delphi XE3 )) but failed in this procedure.
![immagine](https://cloud.githubusercontent.com/assets/16204864/14410830/b26f5da2-ff38-11e5-9a1a-af96f127a08b.png).

Thank you  ;)

**Comment by Pigrecos** [comment]
To delete the error add this code in function FindRTTIs (start lines 844)

`                               if (methodKind)
                                {
                                    //ResultTypeName
                                    len = Code[n]; n += len + 1;
                                    if (len)
                                    {
                                        //ResultType
                                        n += 4;
                                       
                                        //////////////////////////// Insert by Pigrecos 
                                        //AttrData
                                        dw = *((WORD*)(Code + n));
                                        n += dw;//ATR!!
                                    }
                                }
                            }
                        }`

**Comment by crypto2011** [comment]
Pigrecos, thank You. Bug was fixed, also I have corrected all lines of code with AttriibuteData (usually this field had no data, but in one file I have found data in it).

**Comment by Pigrecos** [comment]
thank you so much ;)
