### ISSUE TITLE
Bug for getting event parameters

### ISSUE THREAD

**Issue by csitGenny** [crypto2011/IDR#20]
In IDR, There is a problem that getting the event parameters from KnowledgeBase.
If KnowledgeBase version 2 is correct:
TForm1.FormKeyDown(Sender:TObject; var Key:Word; Shift:TShiftState);

But, if KnowledgeBase version 1, the event parameters can't get:
TForm1.FormKeyDown(?:?; ?:?; ?:?);

**Comment by csitGenny** [comment]
# Modify:

**Comment by crypto2011** [comment]
Thank you, I have modified source files.
