### ISSUE TITLE
Bug in MKnowledgeBase::GetTypeInfo

### ISSUE THREAD

**Issue by csitGenny** [crypto2011/IDR#23]
There is a bug when GetTypeInfo from KBver = 1 sometime. Fixed follow:

MTypeInfo* __fastcall MKnowledgeBase::GetTypeInfo(int ATypeIdx, DWORD AFlags, MTypeInfo *tInfo)
{
	if (!Inited) return 0;

    if (ATypeIdx == -1) return 0;

    const BYTE* p = GetKBCachePtr(TypeOffsets[ATypeIdx].Offset, TypeOffsets[ATypeIdx].Size);

    //Modified by ZGL
    if (Version == 1)
        tInfo->Size = TypeOffsets[ATypeIdx].Size;
    else
    {
        tInfo->Size = *((DWORD*)p); p += 4;
    }
    //---------------

**Comment by crypto2011** [comment]
Thanks

**Comment by jandos** [comment]
Was getting` EAccessViolation` error when trying to decompile Delphi 6 program.
Proposed fix helped.
Thanks!

**Comment by crypto2011** [comment]
What program you tried to decompile? I need example.
