### ISSUE TITLE
Fixed bug for TFMain_11011981::IniFileRead

### ISSUE THREAD

**Issue by csitGenny** [crypto2011/IDR#24]
pos = str.LastDelimiter(",");
        if (pos)
        {
            filename = str.SubString(2, pos - 3);   //Modified by ZGL
            version = str.SubString(pos + 1, str.Length() - pos).ToInt();
        }
        else

**Comment by crypto2011** [comment]
Thank You

**Comment by greenozon** [comment]
This fix was added, lets close this issue?
