### ISSUE TITLE
Feature Request - x86_64 Support

### ISSUE THREAD

**Issue by decidedlygray** [crypto2011/IDR#25]
Hello,

I am guessing it might be a lot of work, but I would just like to add this feature request: support for x64 PE's

**Comment by crypto2011** [comment]
I am working on this subject. It's really huge work.

**Comment by decidedlygray** [comment]
I can only imagine how much work adding a new architecture is. Your hard work is appreciated!

**Comment by crypto2011** [comment]
IDR64 already analyze files, but decompiler need to be rewrited completely.

**Comment by decidedlygray** [comment]
Thanks @greenozon - closing

**Comment by Alexpux** [comment]
Is any reason to create separate repository for 64 bit version? Why not support both 32 and 64 bit in one sources

**Comment by greenozon** [comment]
Despite the same GUI, both apps have absolutely different back-end (analyzer as well as decompiler)
Maybe in the future once both 32 & 64 bit decompilers will be mature enough then it'll make some sense to make the common denominator :)
