### ISSUE TITLE
Compilation bug reintroduced in new version

### ISSUE THREAD

**Issue by BakasuraRCE** [crypto2011/IDR#26]
The commit https://github.com/crypto2011/IDR/commit/8f5ded1257f98a8c9aeec3f7df3c21d48e319df4#diff-ec6e4a38c353eb819ebf6636cbd2d3a9 reintroduce the https://github.com/crypto2011/IDR/pull/21 bug and introduce the files `IdcDialog.res IdcDialog.rc` that not exist in repo

**Comment by crypto2011** [comment]
I have added these files
