### ISSUE TITLE
Alternative development: CBuilder 10.2

### ISSUE THREAD

**Issue by BakasuraRCE** [crypto2011/IDR#27]
I've been working to run the code on Embarcadero C ++ 10.2 Tokyo. Now I have a functional version with a lot of bugs to correct!

If you allow it, could you create a new branch (called `cbuilder-10.2`) in the repository to support this alternative development?

[My branch.](https://github.com/BakasuraRCE/IDR/tree/cbuilder-10.2)

Thanks for your consideration.

**Comment by crypto2011** [comment]
How I would create it? Give ne instructions pls.

**Comment by BakasuraRCE** [comment]
1. On GitHub, navigate to the main page of the repository.
2. Click the branch selector menu.
3. Type a unique name for your new branch.
4. Press Enter.

![image](https://user-images.githubusercontent.com/26231582/27945222-6b945ea4-62b1-11e7-8d03-981af4ed809a.png)

**Comment by crypto2011** [comment]
Ok

**Comment by BakasuraRCE** [comment]
https://github.com/crypto2011/IDR/pull/28

**Comment by crypto2011** [comment]
I have made merging of two branches. How to restore my project?

**Comment by BakasuraRCE** [comment]
I think this should do the job: https://github.com/crypto2011/IDR/pull/31

**Comment by crypto2011** [comment]
Yes, thank you

**Comment by crypto2011** [comment]
I cannot push updated files after creating new branch "cbuilder-10.2". Do I need to create local copy of it on my computer and there?

**Comment by BakasuraRCE** [comment]
You can swap the current working branch from the git console:

Change to master:
`git checkout master`

Change to cbuilder-10.2:
`git checkout cbuilder-10.2`

Then simply do the work with git normally:

```
git add .
git commit -a -m "My new commit"
git push
```

A detailed info [here](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)

**Comment by crypto2011** [comment]
No, I cannot push files in master! I think that it happened after creating new branch. Something wrong. Do I need create local directory "cbuilder-10.2"?

**Comment by BakasuraRCE** [comment]
Already synced your local repository? `git pull`

I just send you an e-mail, please read it.

**Comment by crypto2011** [comment]
Already tried to sync, but it is helpless. I leave this project.

**Comment by BakasuraRCE** [comment]
try creating a local repo from scratch:

```
git clone https://github.com/crypto2011/IDR.git
// Copy your updated files to new folder
git add .
git status
git commit -am "New commit"
git push
```

**Comment by crypto2011** [comment]
Problem was resolved after upgrading Git Bash.
