### ISSUE TITLE
Cannot find initialization table error

### ISSUE THREAD

**Issue by hypnz** [crypto2011/IDR#34]
Hi crypto
When i try to decompile this file https://mega.nz/#!4RJ1VB6K!zIlOn__vSnCHbB2Eq2wtUDDChl_l5wi0M0X2CDcwWbk i get this error.

**Comment by crypto2011** [comment]
IDA has determined that your file written in vc7. IDR can analyze only files written in Delphi.

**Comment by hypnz** [comment]
Thx for your replying man. Aha. I c. Ident showed that is delphi.

**Comment by fenderluvr** [comment]
This bug is still valid.  Problem occurs when EP has been manipulated/invalid.

**Comment by Silv3rSamurai** [comment]
Tried to analyze something that's delphi made (since eda_preview is showing T***s on classname but still gets this error. Any update on this error?
