### ISSUE TITLE
Add support for Delphi 8?

### ISSUE THREAD

**Issue by ksmiller99** [crypto2011/IDR#39]
How much effort would be needed to add support for Delphi 8? How can I be sure that my DLL to be decompiled is, in fact, Delphi 8? There is a static string `'Delphi%.8X'` in the disassembly. Any tips or suggestions would be greatly appreciated.

**Comment by crypto2011** [comment]
Delphi 8 has NET-architecture, IDR process only native. I have no reason (and time) to write completely new application for NET.

**Comment by greenozon** [comment]
.NET was not the best idea for Delphi and it was highly criticized and not accepted by community.

https://en.wikipedia.org/wiki/Delphi_(IDE)#Borland_Delphi_8

@ksmiller99,
for investigating .net assemblies, you better use .net based tools like dnSpy, ILSpy, .NET Reflector, etc
