### ISSUE TITLE
Project LICENSE

### ISSUE THREAD

**Issue by upiter** [crypto2011/IDR#40]
# License is missing

To project author @crypto2011:

Please, specify **LICENSE** for IDR project.
See [Licensing a repository](https://help.github.com/articles/licensing-a-repository/) and [Choose an open source license](https://choosealicense.com) for more information.

Currently IDR project has [no license specified](https://github.com/crypto2011/IDR/search?q=License&unscoped_q=License).

**Comment by crypto2011** [comment]
License was added
