### ISSUE TITLE
IDR is not DPI aware

### ISSUE THREAD

**Issue by greenozon** [crypto2011/IDR#43]
IDR GUI is really very very huge in case W10 is doing scaling by means of OS, 
it is not possible to work in that use-case
example:

http://prntscr.com/m4cgi2

**Comment by csitGenny** [comment]
void __fastcall ScaleForm(TForm* AForm)
{
    HDC _hdc = GetDC(0);
    if (_hdc)
    {
        //Modified by ZGL
        int LogicalScreenHeight = GetDeviceCaps(_hdc, VERTRES);
        int PhysicalScreenHeight = GetDeviceCaps(_hdc, DESKTOPVERTRES);
        AForm->ScaleBy(PhysicalScreenHeight, LogicalScreenHeight);
        //Modified end
        ReleaseDC(0, _hdc);
    }
}

**Comment by crypto2011** [comment]
Modified. Thank you.
