### ISSUE TITLE
How idr and IDA PRO connected ?

### ISSUE THREAD

**Issue by maxben14** [crypto2011/IDR#44]
I disassemble the library in IDR, and debug in IDA pro. How do the results of disassembling from IDR are inserted into ida pro? I make the script, but it breaks the whole code analysis into the IDA.

**Comment by LordNoteworthy** [comment]
Go to IDR -> Tools -> IDC Generator, once the idc get generated, load it in IDA.

**Comment by crypto2011** [comment]
IDR->Tools->Create C header file
