### ISSUE TITLE
Cannot initialize Disasm

### ISSUE THREAD

**Issue by qux-bbb** [crypto2011/IDR#47]
When I start it on Windows 10 or Windows 7. It shows "Cannot initialize Disasm".  
![image](https://user-images.githubusercontent.com/18598419/55058095-fdd60b80-50a5-11e9-97c0-33783a504ece.png)  

![image](https://user-images.githubusercontent.com/18598419/55058151-278f3280-50a6-11e9-94a2-9f52844fbe23.png)  

What should I do?

**Comment by crypto2011** [comment]
Check existance file dis.dll in IDR directory

**Comment by qux-bbb** [comment]
Thanks, that works by "git clone" the whole project.
When I saw "The program does not require any installation activity and does not do any records in Windows registry." in README.md, I thought that's OK for downloading the exe on releases page and using it directly.

**Comment by crypto2011** [comment]
You are right. I will write it in readme file
