### ISSUE TITLE
Unit renaming inconsistency

### ISSUE THREAD

**Issue by AHOHNMYC** [crypto2011/IDR#55]
An old name is still displayed in `CodeViewer` tab after unit renaming (of course, if there was opened some method from renamed unit).
![1](https://user-images.githubusercontent.com/24810600/78456569-25928300-76ad-11ea-87a6-3c59ff4b2ef7.png)

**Comment by crypto2011** [comment]
Fixed

**Comment by AHOHNMYC** [comment]
Thank you for great tool and fast response :smile_cat:
