### ISSUE TITLE
can not open knowledge base file 

### ISSUE THREAD

**Issue by mohamad-islam** [crypto2011/IDR#57]
Hi, first of all, thank you for your great work.
I have a malware analysis homework and I'm trying to get the source code of the malware 
when I used PEiD it told me that the malware is using Delphi 6 -7 (screenshot)
![image](https://user-images.githubusercontent.com/57301610/81125595-4581c480-8f41-11ea-940b-33bbd497feda.png)
![image](https://user-images.githubusercontent.com/57301610/81125576-39960280-8f41-11ea-9da4-f5a7527f91e2.png)
when I'm trying to use IDR I'm getting the following message, I went to the directory and didn't find the file kb2007.bin but found syskb2007.bin
what can I do to fix the problem 
best regards

**Comment by piratesephiroth** [comment]
https://www.dropbox.com/sh/9ran313nidqtagb/AADl_m_9GVYSiXUviZtDQWQHa?dl=0

**Comment by sergiojrdotnet** [comment]
Link is broken

**Comment by sergiojrdotnet** [comment]
@piratesephiroth @crypto2011 Link is broken

**Comment by crypto2011** [comment]
Guys from dropbox don't like that my box has a big traffic. So I will move tomorrow all knowledge base files to another location.

**Comment by ScootaDaBuddah** [comment]
im having this same problem and the like @piratesephiroth posted did not help. should I just remove the sys from the front to make it work?

**Comment by 404alya** [comment]
same for me
