### ISSUE TITLE
knowledge base file problem?

### ISSUE THREAD

**Issue by Harshil783** [crypto2011/IDR#60]
Hey! help me for installation and issue is cannot open knowledge base file incorrect version?
**All knowledge base files are there in directory then why?**

![Capture](https://user-images.githubusercontent.com/52579448/84296053-19251d80-ab69-11ea-9eba-85f5d44bb215.PNG)

**Comment by Hlancan** [comment]
@Harshil783 I encountered the same problem, how did you solve this problem?
