### ISSUE TITLE
Error: Assertion failed: num < ModuleCount (KnowledgeBase.cpp)

### ISSUE THREAD

**Issue by Nordes** [crypto2011/IDR#67]
While running the application I get the following:

![image](https://user-images.githubusercontent.com/446572/114558229-75991380-9c38-11eb-9c1e-f1d94ace1ad6.png)

Do I need to recompile the IDR before running it?

**Comment by crypto2011** [comment]
Usually no. If you want I can try to check your file.

**Comment by Nordes** [comment]
Ok, for now I guess it will be ok, so no need to check the file. I was only wondering why I hit this kind of error (which is a bit weird).

Thanks for your quick reply.
