### ISSUE TITLE
error with terminate

### ISSUE THREAD

**Issue by Mabus13** [crypto2011/IDR#68]
![image](https://user-images.githubusercontent.com/4775305/116402504-2c9aaf00-a835-11eb-9e00-37294f1caaff.png)

**Comment by Mabus13** [comment]
![image](https://user-images.githubusercontent.com/4775305/116404285-2ad1eb00-a837-11eb-9c08-e4029e656727.png)

**Comment by Mabus13** [comment]
![image](https://user-images.githubusercontent.com/4775305/116404381-3de4bb00-a837-11eb-9130-1f311834369a.png)

**Comment by dxon** [comment]
Got same thing

**Comment by Mabus13** [comment]
yep T_T where crypto2011 ???

**Comment by dxon** [comment]
I've fixed it. Get kb* files via link to Dropbox at the end of Readme and unpack them all in folder where .exe file placed. Then run program.

**Comment by Mabus13** [comment]
kek lol, i used syskb... think that all file for all =))))) yes, need use few files
