### ISSUE TITLE
How to build the project

### ISSUE THREAD

**Issue by Vespasian** [crypto2011/IDR#71]
Is there any hint you could give on how to build the project.

What tool do I use?

**Comment by crypto2011** [comment]
Don't understand. What you mean?

**Comment by Vespasian** [comment]
Thanks for your reply
How do I get started building the exe
what tools do I need?
 I guess c++ builder?
 however it's unclear what commands I have to call.

**Comment by Vespasian** [comment]
Nevermind I'm didn't read the README correctly.
