### ISSUE TITLE
Can we get a build of this in the bin directory?

### ISSUE THREAD

**Issue by valdier1** [crypto2011/IDR#75]
Building the project with Borland c++ is fairly difficult to achieve these days. I've been searching for a way to do this for 2 days. The Embarcado RAD studio can't do it, and all references to Borland point to that, that I can find.

**Comment by crypto2011** [comment]
Fresh version of IDR is in bin directory

**Comment by crypto2011** [comment]
Dll's were added

**Comment by crypto2011** [comment]
Done
