### ISSUE TITLE
Problem with Knowledge Base

### ISSUE THREAD

**Issue by dzekos7** [crypto2011/IDR#79]
Every time I run the Autodetect Version it shows me this error "Cannot open Knowledge Base file C:\Users\..kb2010.bin (may be incorrect Version). I delete all files and download them again but the issue is still persist. What i have to do to fix it?

**Comment by kwisatz** [comment]
Did you read the readme and where to download the kb files from?

**Comment by dzekos7** [comment]
I found it already but i forget to write it here. Thank you
