### ISSUE TITLE
"Cannot find initialization table" when importing a Delphi2 exe

### ISSUE THREAD

**Issue by bostick** [crypto2011/IDR#86]
I am trying to load the attached .exe file but I am getting the "Cannot find initialization table" error

[TabIt-2.03-trial.exe.zip](https://github.com/crypto2011/IDR/files/11637361/TabIt-2.03-trial.exe.zip)

PEiD says it is Borland Delphi 2.0

**Comment by crypto2011** [comment]
Try to choose delphi2, not automatic option of load file.

пт, 2 июн. 2023 г., 19:57 Brenton Bostick ***@***.***>:

**Comment by bostick** [comment]
Yes, I did try delphi2 (and others as well, just to see what happened).

Does the executable load for you using delphi2?

**Comment by bostick** [comment]
I see that this is packed in a weird way and will have to be unpacked first. So I am closing this issue.
