### ISSUE TITLE
Request: Add knowledge bases to the Github Repository

### ISSUE THREAD

**Issue by Ana06** [crypto2011/IDR#87]
My team (FLARE team, part of Mandiant/Google) find IDR very useful when analysing Delphi malware. We have added it to [VM-Packages](https://github.com/mandiant/VM-Packages) and as a default [FLARE-VM](https://github.com/mandiant/flare-vm) tool.

It seems the only place where we can download knowledge bases from is Google Drive:
> Knowledge bases for various Delphi versions can be found at:
> https://drive.google.com/drive/folders/1IBsO1_O9xGHkPPV9Pnqkq2uoFmuak5C7?usp=sharing

But Google drive is not meant to be used in scripts and downloading the files from Google Drive doesn't seem to always work:
```
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://drive.google.com/u/0/uc?id=16PREPxK6gJINAFC7TvS4k6qtXiZ71aEr&export=download'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (403) Forbidden."
```

It would be ideal if the knowledge bases were added to this GitHub repository, so that we don't have to download them from Google Drive. @crypto2011 is there any other place we can download the knowledge bases from? is there any chance you can add the knowledge bases to this GitHub repository? Either together with the source code or as part of a release would be fine.

This issue is tracked in VM-Packages at: https://github.com/mandiant/VM-Packages/issues/430

**Comment by crypto2011** [comment]
Done.

**Comment by Ana06** [comment]
That was fast! 🚀  Thank you so much! :blush: I think it would be good to have all of them, as I assume that using the correct version will provide better results.

**Comment by crypto2011** [comment]
All done.

**Comment by Ana06** [comment]
Thank you!!!! 😊 We can close this issue. 👍
