### ISSUE TITLE
Suspicious code in TFMain_11011981::FindText

### ISSUE THREAD

**Issue by tmcdos** [crypto2011/IDR#9]
In file **Main.cpp** in function **TFMain_11011981::FindText** in **case SEARCH_NAMES** there are
`pos = line.Pos("'"); `
But lines in **lbNames** are composed from address, item name, colon and item type - there are no quotes, if this is ResourceString; and there are multiple quotes, if this is AnsiString and contains non-latin characters. It seems that the piece of code is copy-pasted from **case SEARCH_STRINGS** - but here there is no need for **Pos()** and **Substring()**, this even seems wrong.

**Comment by crypto2011** [comment]
You are right. Result of copy+paste.
